### ISSUE TITLE
Provide Ease of Rolling Plot Dice

### ISSUE THREAD

**Issue by Khunkurisu** [Khunkurisu/cosmere-rpg-workbench#1]
~~Title. Not sure if possible with the current system api and hooks but worth trying.~~

Original title specified hooking into the actor sheet to display it, but discussions below have provided alternative ideas to explore.

**Comment by Dez384** [comment]
As an alternative to trying to inject a button into the actor sheet, you could take an idea from the *Dice Tray* module and turn the D20 icon in the chat controls into a button that will roll a plot die. You could use CSS to swap out the icon with the plot die symbol to make it obvious.

**Comment by Khunkurisu** [comment]
I don’t hate this idea, but I’d like the method to not conflict with modules like Dice Tray, which tend to disable/override that part of the UI.

**Comment by Dez384** [comment]
If a GM is using *Dice Tray*, then they don’t need a button for rolling a plot die, they can just configure *Dice Tray*. 

My thoughts were along the lines of the button not being in the actor sheet would make it easier for players and GMs to find and not as likely to break integration when the actor sheet changes. 

My second idea would be to put a tool in the token layer controls. Players generally don’t move off the token layer and GMs would know where to find it.

**Comment by Khunkurisu** [comment]
I’ve never had to configure Dice Tray for a game with custom dice mechanics before so that’s good to know. These are all good suggestions, I’ll look into which ones work out best. If I manage to figure out how the Dice Tray side works I may even be able to automatically generate the plot die for it if I detect it’s one of the active modules.

**Comment by Khunkurisu** [comment]
Also of note this was a request from a user in the system’s discord, which is why I started with the sheet idea.

**Comment by Khunkurisu** [comment]
I added an option to the sheet for this and in testing, it didn't add much convenience. I may steal out of [PF2e Toolbelt's](https://github.com/reonZ/pf2e-toolbelt), well, toolbelt, and implement an optional dicetray. People who prefer the Dice Tray module can of course just use and set up that.
